version: '3'

services:

  sing-box:
    container_name: sing-box
    image: ghcr.io/sagernet/sing-box:latest
    restart: always
    network_mode: host
    privileged: true
    devices:
      - /dev/net/tun
    volumes:
      - ./sing-box:/data
    depends_on:
      - naive
    command: run -c /data/config.json

  # haproxy:
  #   container_name: haproxy
  #   image: haproxy:alpine
  #   restart: always
  #   volumes:
  #     - ./haproxy:/usr/local/etc/haproxy
  #   ports:
  #     - 1080:1080/tcp
  #     - 1080:1080/udp

  naive:
    container_name: naive
    image: kwaabot/naive
    restart: always
    volumes:
      - ./naive/config.json:/etc/naive/config.json
    # expose:
    #   - '1080'
    ports:
      - 1080:1080/tcp
      - 1080:1080/udp

